package com.treelzebub.readerbility.auth.async;

import android.app.Activity;
import android.content.Intent;
import android.os.AsyncTask;

import com.treelzebub.readerbility.api.Readability;
import com.treelzebub.readerbility.ui.fragtivity.Library;

import org.scribe.model.Token;
import org.scribe.model.Verifier;

import java.lang.ref.WeakReference;

/**
 * Created by Tre Murillo on 3/22/15
 *
 * An AsyncTask that takes a Verifier generated by user input of auth code
 * after successful login on API website.
 */
public class SetAccessToken extends AsyncTask<Verifier, Void, Token> {
    private final Readability instance;
    private final WeakReference<Activity> mActivityReference;

    public SetAccessToken(Activity activity) {
        this.mActivityReference = new WeakReference<>(activity);

        instance = Readability.getInstance();
    }

    @Override
    protected Token doInBackground(Verifier... params) {
        Token requestToken = instance.getService().getRequestToken();

        return instance.getService().getAccessToken(requestToken, params[0]);
    }

    @Override
    protected void onPostExecute(Token token) {
        super.onPostExecute(token);
        Activity activity = mActivityReference.get();

        Readability.setAccessToken(token);
        activity.startActivity(new Intent(activity, Library.LibraryActivity.class));
    }
}