package com.treelzebub.readerbility.auth.async;

import android.content.Intent;
import android.os.AsyncTask;
import android.widget.Toast;

import com.codepath.oauth.OAuthLoginActionBarActivity;
import com.treelzebub.readerbility.api.Readability;
import com.treelzebub.readerbility.ui.fragtivity.Library;

import org.scribe.model.Token;
import org.scribe.model.Verifier;

/**
 * Created by Tre Murillo on 3/22/15
 *
 * An AsyncTask that takes a Verifier generated by user input of auth code
 * after successful login on API website.
 */
public class SetAccessToken extends AsyncTask<Verifier, Void, Token> {
    private final Readability instance;
    private final OAuthLoginActionBarActivity mActivity;

    public SetAccessToken(OAuthLoginActionBarActivity mActivity) {
        this.mActivity = mActivity;
        instance = Readability.getInstance();
    }

    @Override
    protected Token doInBackground(Verifier... params) {
        Token requestToken = instance.getService().getRequestToken();
        String tokenBody = requestToken.getRawResponse();

        Toast.makeText(mActivity, tokenBody, Toast.LENGTH_LONG).show();

        return instance.getService().getAccessToken(requestToken, params[0]);
    }

    @Override
    protected void onPostExecute(Token token) {
        super.onPostExecute(token);
        Readability.setAccessToken(token);
        mActivity.startActivity(new Intent(mActivity, Library.LibraryActivity.class));
    }
}