package com.treelzebub.readerbility.auth.async;

import android.os.AsyncTask;

import com.treelzebub.readerbility.api.Readability;

import org.scribe.model.Token;
import org.scribe.model.Verifier;

/**
 * Created by Tre Murillo on 3/22/15
 *
 * An AsyncTask that takes a Verifier generated by user input of auth code
 * after successful login on API website.
 */
public class SetAccessToken extends AsyncTask<Verifier, Void, Token> {
    Readability instance = Readability.getInstance();

    @Override
    protected Token doInBackground(Verifier... params) {
        Token requestToken = instance.getService().getRequestToken();

        return instance.getService().getAccessToken(requestToken, params[0]);
    }

    @Override
    protected void onPostExecute(Token token) {
        super.onPostExecute(token);
        Readability.setAccessToken(token);
    }
}